apiVersion: v1
kind: Service
metadata:
  name: {{ values.name }}-metrics
  namespace: {{ values.name }}
  labels:
    app: {{ values.name }}
    metrics: "true"
spec:
  selector:
    app: {{ values.name }}
  ports:
  - name: metrics
    port: 9090
    targetPort: 9090
    protocol: TCP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ values.name }}
  namespace: {{ values.name }}
  labels:
    app: {{ values.name }}
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: {{ values.name }}
      metrics: "true"
  endpoints:
  - port: metrics
    interval: 30s
    path: /metrics
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ values.name }}
  namespace: {{ values.name }}
  labels:
    app: {{ values.name }}
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: {{ values.name }}
  podMetricsEndpoints:
  - port: metrics
    interval: 30s
    path: /metrics
